# Generated by Django 3.1.4 on 2021-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('sport', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
